### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GOD-oda** [GOD-oda/slack_blocks_builder#1]
## Blocks
- [ ] [ActionsBlock](https://api.slack.com/reference/block-kit/blocks#actions)
  - [x] [ButtonElement](https://api.slack.com/reference/block-kit/block-elements#button)
  - [ ] [CheckboxGroups](https://api.slack.com/reference/block-kit/block-elements#checkboxes)
  - [ ] DatePickerElement
  - [ ] OverflowMenuElement
  - [ ] RadioButtonGroupElement
  - [ ] [SelectMenuElement](https://api.slack.com/reference/block-kit/block-elements#select)
    - [x] [StaticOptions](https://api.slack.com/reference/block-kit/block-elements#static_select)
    - [ ] [ExternalDataSource](https://api.slack.com/reference/block-kit/block-elements#external_select)
    - [ ] [UserList](https://api.slack.com/reference/block-kit/block-elements#users_select)
    - [ ] ConversationsList
    - [ ] PublicChannelsList
  - [ ] TimePickerElement
- [x] [ContextBlock](https://api.slack.com/reference/block-kit/blocks#context)
- [x] DividerBlock
- [ ] FileBlock
- [x] [HeaderBlock](https://api.slack.com/reference/block-kit/blocks#header)
- [x] [ImageBlock](https://api.slack.com/reference/block-kit/blocks#image)
- [ ] InputBlock
  - [ ] CheckboxGroups
  - [ ] DatePickerElement
  - [ ] MultiSelectMenuElement
    - [ ] StaticOptions
    - [ ] ExternalDataSource
    - [ ] UserList
    - [ ] ConversationsList
    - [ ] PublicChannelsList
  - [ ] PlainTextInputElement
  - [ ] RadioButtonGroupElement
  - [ ] SelectMenuElement
    - [ ] StaticOptions
    - [ ] ExternalDataSource
    - [ ] UserList
    - [ ] ConversationsList
    - [ ] PublicChannelsList
  - [ ] TimePickerElement
- [ ] SectionBlock
  - [ ] [ButtonElement](https://api.slack.com/reference/block-kit/block-elements#button)
  - [ ] CheckboxGroups
  - [ ] DatePickerElement
  - [ ] ImageElement
  - [ ] MultiSelectMenuElement
    - [ ] StaticOptions
    - [ ] ExternalDataSource
    - [ ] UserList
    - [ ] ConversationsList
    - [ ] PublicChannelsList
    - [ ] OverflowMenuElement
  - [ ] RadioButtonGroupElement
  - [ ] SelectMenuElement
    - [ ] StaticOptions
    - [ ] ExternalDataSource
    - [ ] UserList
    - [ ] ConversationsList
    - [ ] PublicChannelsList
  - [ ] TimePickerElement

### [ActionBlock](https://api.slack.com/reference/block-kit/blocks#actions)
|key|Type|Required|
-|-|-
|type|string|yes|
|elements|Object[]|yes|
|block_id|string|no|

- elements
  - can use button object, select menus, overflow menus, or date pickers
  - There is a maximum of 5 elements in each action block.

### [ContextBlock](https://api.slack.com/reference/block-kit/blocks#context)
|key|Type|Required|
-|-|-
|type|string|yes|
|elements|Objects[]|yes|
|block_id|string|no|

- elements
  - An array of image elements and text objects.
  - Maximum number of items is 10.
- block_id
  - Maximum length for this field is 255 characters

### [DividerBlock](https://api.slack.com/reference/block-kit/blocks#divider)
|key|Type|Required|
-|-|-
|type|string|yes|
|block_id|string|no|

- block_id
  - Maximum length for this field is 255 characters.

### [HeaderBlock](https://api.slack.com/reference/block-kit/blocks#header)
|key|Type|Required|
-|-|-
|type|string|yes|
|text|Object|yes|
|block_id|string|no|

- text
  - The text for the block, in the form of a plain_text text object.
  - Maximum length for the text in this field is 150 characters.
- block_id
  - Maximum length for this field is 255 characters.

### [ImageBlock](https://api.slack.com/reference/block-kit/blocks#image)
|key|Type|Required|
-|-|-
|type|string|yes|
|image_url|string|yes|
|alt_text|string|yes|
|title|Object|no|
|block_id|string|no|

- image_url
  - Maximum length for this field is 3000 characters.
- alt_text
  - Maximum length for this field is 2000 characters.
- title
  - can only be of type: plain_text.
  - Maximum length for the text in this field is 2000 characters.
- block_id
  -  Maximum length for this field is 255 characters. 

### [ButtonElement](https://api.slack.com/reference/block-kit/block-elements#button)
|key|type|required|
-|-|-
|type|string|yes|
|text|TextObject|yes|
|action_id|string|no|
|url|string|no|
|value|string|no|
|style|string|no|
|confirm|ConfirmObject|no|

### [StaticOptionsSelectMenu](https://api.slack.com/reference/block-kit/block-elements#static_select)
|key|type|required|
-|-|-
|type|string|yes|
|placeholder|TextObject|yes|
|action_id|string|yes|
|options|Object[]|yes|
|option_groups|Object[]|no|
|initial_option|string|no|
|confirm|ConfirmObject|no|
|focus_on_load|bool|no|

- placeholder
  - only text object 
  - Maximum number of options is 100
- action_id
  - Maximum length for this field is 255 characters.
- options
  - Maximum number of options is 100.
  - option_groups is specified, this field should not be.
- option_groups
  - Maximum number of option groups is 100
  - options is specified, this field should not be.
- initial_option
  - A single option that exactly matches one of the options within options or option_groups.

### [ImageElement](https://api.slack.com/reference/block-kit/block-elements#image)
|key|type|required|
-|-|-
|type|string|yes|
|image_url|string|yes|
|alt_text|string|yes|

### [TextObject](https://api.slack.com/reference/block-kit/composition-objects#text)
- type: string
  - `plain_text` or `mrkdwn`
- text: string
- emoji: bool
  - only usable when `plain_text`
- verbatim: bool
  - only usable when `mrkdwn`

### [ConfirmationDialogObject](https://api.slack.com/reference/block-kit/composition-objects#confirm)
- title: string
  - plain text object only
  - up to 100 characters
- text: string
  - plain text object or markdown text object
  - up to 300 characters
- confirm: TextObject
  - plain text object only
  - up to 30 characters
- deny: TextObject
  - plain text object only
  - up to 30 characters
- style: string
  - primary or danger
  - default is primary

### [OptionObject](https://api.slack.com/reference/block-kit/composition-objects#option)
|key|type|
-|-
|text|TextObject|
|value|string|
|description|TextObject|
|url|string|

- text
  - Overflow, select, and multi-select menus can only use plain_text objects, while radio buttons and checkboxes can use mrkdwn text objects.
  - Maximum length for the text in this field is 75 characters.
- value
  - Maximum length for this field is 75 characters.
- description
  - A plain_text only text object that defines a line of descriptive text shown below the text field beside the radio button.
  - Maximum length for the text object within this field is 75 characters.

### [OptionGroupObject](https://api.slack.com/reference/block-kit/composition-objects#option_group)
|key|type|required|
-|-|-
|labelTextObject|yes|
|options|Objects[]|yes|

- label
  - A plain_text only text object
  - Maximum length for the text in this field is 75 characters.
- options
  - Maximum of 100 items.

### [DispatchActionConfiguration](https://api.slack.com/reference/block-kit/composition-objects#dispatch_action_config)
- trigger_actions_on: string[]

### [FilterObjectForConversationLists](https://api.slack.com/reference/block-kit/composition-objects#filter_conversations)
- include: string[]
- exclude_external_shared_channels: bool
- exclude_bot_users: bool
